<a href="https://colab.research.google.com/github/MrOyieyo/Data-Analysis-Project/blob/main/Python_Gym_Olympics1_Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import psycopg2
import pandas as pd

In [66]:
# Replace the following connection string with your actual database URL
db_url = "postgres://student:tAdJApZJw7X3C%40xs@ep-noisy-flower-846766.us-east-2.aws.neon.tech/olympics"

try:
    # Establish a connection to the PostgreSQL server using the URL
    connection = psycopg2.connect(db_url)

    # Create a cursor to interact with the database
    cursor = connection.cursor()

    # Execute SQL queries
    cursor.execute("SELECT version();")
    version = cursor.fetchone()
    print("Connected to PostgreSQL version:", version)

    cursor.close()

except psycopg2.Error as e:
    print("Error connecting to the database:", e)

Connected to PostgreSQL version: ('PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit',)

In [67]:
# Create a cursor to interact with the database
cursor = connection.cursor()

# Execute SQL query to select data from the database
query = "SELECT * FROM athletes_events;"
cursor.execute(query)

# Fetch all the selected data into a list of tuples
data = cursor.fetchall()

# Get column names from the cursor description
column_names = [desc[0] for desc in cursor.description]

# Define the data types for each column in a dictionary
dtype_mapping = {
    'weight': 'float'
}

# Create a Pandas DataFrame from the selected data and column names with specified data types
df = pd.DataFrame(data, columns=column_names).astype(dtype_mapping)

# Don't forget to close the cursor and the connection
cursor.close()
connection.close()

df.head()

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,None
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,None
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,None

**1. Create a new dataframe called "summer_games_df" that filters Summer games.**

In [15]:
summer_game_df= df[(df.season=="Summer")].copy()
summer_game_df

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,None
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,None
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271106,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,None
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,None
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,None
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,None
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,None

**2. Subset this new dataframe to only include the following columns:
name, teams, games, sport and medal**

In [19]:
summer_game_df=summer_game_df[["name","team","games","sport","medal"]]
summer_game_df

,name,team,games,sport,medal
0,A Dijiang,China,1992 Summer,Basketball,None
1,A Lamusi,China,2012 Summer,Judo,None
2,Gunnar Nielsen Aaby,Denmark,1920 Summer,Football,None
3,Edgar Lindenau Aabye,Denmark/Sweden,1900 Summer,Tug-Of-War,Gold
26,"Cornelia ""Cor"" Aalten (-Strannood)",Netherlands,1932 Summer,Athletics,None
...,...,...,...,...,...
271106,Fernando scar Zylberberg,Argentina,2004 Summer,Hockey,None
271107,"James Francis ""Jim"" Zylker",United States,1972 Summer,Football,None
271108,Aleksandr Viktorovich Zyuzin,Russia,2000 Summer,Rowing,None
271109,Aleksandr Viktorovich Zyuzin,Russia,2004 Summer,Rowing,None
271110,Olga Igorevna Zyuzkova,Belarus,2016 Summer,Basketball,None

**3. Creating a new df, china_gold_df, that subsets summer_games_df by the teams from China where a gold medal was won**

In [64]:
china_gold_df=summer_game_df[(summer_game_df.team=="China") & (summer_game_df.medal=="Gold")].copy()
china_gold_df

               name   team        games          sport medal
33531     Cai Yalin  China  2000 Summer       Shooting  Gold
34915       Cao Lei  China  2008 Summer  Weightlifting  Gold
34933      Cao Yuan  China  2012 Summer         Diving  Gold
34934      Cao Yuan  China  2016 Summer         Diving  Gold
39195    Chen Aisen  China  2016 Summer         Diving  Gold
...             ...    ...          ...            ...   ...
270433      Zou Kai  China  2008 Summer     Gymnastics  Gold
270434      Zou Kai  China  2012 Summer     Gymnastics  Gold
270435      Zou Kai  China  2012 Summer     Gymnastics  Gold
270439  Zou Shiming  China  2008 Summer         Boxing  Gold
270440  Zou Shiming  China  2012 Summer         Boxing  Gold

[294 rows x 5 columns]

** 4. Using the original dataframe df, what sports has Namibia competed in?**

In [62]:
df_f=df[df["team"]=="Namibia"]["sport"].unique().copy()

df_f

array(['Cycling', 'Shooting', 'Boxing', 'Athletics', 'Swimming',
       'Gymnastics', 'Wrestling'], dtype=object)

**5. Using the original dataframe create a new dataframe, clean_df, that cleans up team names (China-1 -> China, China-2 -> China. China-3 -> China)**

In [70]:
clean_df = df.copy()
clean_df["team"].replace({'China-1': 'China', 'China-2': 'China', 'China-3': 'China'})
clean_df["team"]

0                  China
1                  China
2                Denmark
3         Denmark/Sweden
4            Netherlands
               ...
271111          Poland-1
271112            Poland
271113            Poland
271114            Poland
271115            Poland
Name: team, Length: 271116, dtype: object